engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  checks:
    no-undef:
      enabled: false
    Identical code:
      enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "src/module.js"
    - "src/app.js"
    - "src/invertedindex.js"
    - "spec/dplex-test-spec.js"
languages:
  JavaScript: true
exclude_paths:
- "css/bootstrap.css"
- "animate.css"
- "style.css"
- "src/images"
- .gitignore
- .eslintignore
- .travis.yml
- .eslintrc.json
- "spec/"
- "build/bundle.js"
- "server.js"