engines:
  duplications:
    enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  checks:
    comma-dangle:
      enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "src/app.js"
    - "src/invertedindex.js"
    - "spec/dplex-test-spec.js"
exclude_paths:
- "css/"
- .gitignore
- .eslintignore
- .travis.yml
- .eslintrc
- "spec/lib"
- "spec/support"
- "spec/SpecRunner.html"
- "src/"
