engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
  checks:
    comma-dangle:
      enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "src/app.js"
    - "src/invertedindex.js"
    - "spec/dplex-test-spec.js"
languages:
  JavaScript: true
exclude_paths:
- "css/"
- .gitignore
- .eslintignore
- .travis.yml
- .eslintrc
- "spec/lib"
- "spec/support"
- "spec/SpecRunner.html"
- "src/"