engines:
  duplications:
    enabled: false
    config:
      languages:
        #mass_threshold: 30
        - javascript
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      comma-dangle:
        enabled: false
      import/no-unresolved:
        enabled: false
      no-console:
        enabled: false
      strict:
        enabled: false
      no-unused-vars:
        enabled: false
      no-undef:
        enabled: false
      class-methods-use-this:
        enabled: false
      no-param-reassign:
        enabled: false
      array-callback-return:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
    - "public/builds/*"
languages:
  JavaScript: true
exclude_paths:
- "samples/*"
- "js/*"
- "src/app.js"
- "css/*"
- "node_modules/*"
- "index.html"
- "specs/*"
- .travis.yml
- .eslintrc
- .babelrc
- .env
- "test.js"
- "testclass.js"